package co.com.newpandatv.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import co.com.newpandatv.dao.SQLBeans;

import co.com.newpandatv.dao.SQLBeansDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig sQLBeansDaoConfig;

    private final SQLBeansDao sQLBeansDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        sQLBeansDaoConfig = daoConfigMap.get(SQLBeansDao.class).clone();
        sQLBeansDaoConfig.initIdentityScope(type);

        sQLBeansDao = new SQLBeansDao(sQLBeansDaoConfig, this);

        registerDao(SQLBeans.class, sQLBeansDao);
    }
    
    public void clear() {
        sQLBeansDaoConfig.clearIdentityScope();
    }

    public SQLBeansDao getSQLBeansDao() {
        return sQLBeansDao;
    }

}
